# action.yml
name: 'balena-ci'
description: 'Automate release build and deployments'
inputs:
  balena_token:
    description: 'Your balenaCloud API token'
    required: true
  fleet:
    description: 'Name of the fleet you want to build the release for'
    required: true
  github_token:
    description: 'Github access token'
    required: false
    default: ${{ github.token }}
  environment:
    description: 'Domain for the backend services to build your release'
    required: false
    default: 'balena-cloud.com'
  versionbot:
    description: 'Does the repository use Versionbot ?'
    required: false
    default: false
  finalize:
    description: 'Should the action finalize a release after building'
    required: false
    default: true
  create_ref:
    description: 'Attempt to tag the git commit with the release version'
    required: false
    default: false
  cache:
    description: 'If a release matching the commit already exists do not build'
    required: false
    default: true
  source:
    description: 'Specify custom source path relative to workspace to build in'
    required: false
    default: ''
outputs:
  release_id:
    description: 'ID of the release built'
  version:
    description: 'Version of the release built'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    BALENA_TOKEN: ${{ inputs.balena_token }}
    BALENA_URL: ${{ inputs.environment }}
